database:
  connection_string: ${DATABASE_URL:postgresql://user:pass@localhost/company_db}
  pool_size: 10

embeddings:
  model: "sentence-transformers/all-MiniLM-L6-v2"
  batch_size: 32
  chunk_size: 512

cache:
  ttl_seconds: 300
  max_size: 1000

server:
  host: "0.0.0.0"
  port: 8000
  workers: 1

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
